### PR TITLE
Fixes #27

### LINKED ISSUE #27: Logs report that neither recruiter nor applicant was logged in
Logs report that neither recruiter nor applicant was logged in.

This is most likely caused by `PersonService.java`.

A possible fix would be to throw an error if the person can't be found so that the logging code won't be reached in the case of a failed login.

### PR DESCRIPTION
**Pull request by Cactu5**
Fixes #27

### CODE REVIEW

File: src/main/java/se/kth/iv1201/group4/recruitment/application/PersonService.java [hunk 1]
```diff
@@ -137,21 +138,26 @@ public UserDetails loadUserByUsername(String username) throws UsernameNotFoundEx
...
+                    // either applicants or recruiters
+                    LOGGER.warn("Person logged in as neither an applicant nor recruiter.");
+                    throw new UsernameNotFoundException("User has no role");
+                }
             } else {
-                // Should never end up here as all Persons are
-                // either applicants or recruiters
-                LOGGER.warn("Person logged in as neither an applicant nor recruiter.");
-                throw new UsernameNotFoundException("user has no role");
+                LOGGER.warn("No person with the username " + username + " and password combination could be found.");
```
Comment (Mechakhan) [inline src/main/java/se/kth/iv1201/group4/recruitment/application/PersonService.java:155]: I think the debug level of this print could be lowered to at least `info`, as it should be fairly common for users to enter incorrect credentials.

File: src/main/java/se/kth/iv1201/group4/recruitment/application/PersonService.java [hunk 2]
```diff
@@ -137,21 +138,26 @@ public UserDetails loadUserByUsername(String username) throws UsernameNotFoundEx
...
+                throw new UsernameNotFoundException("Username not found.");
```
Comment (william-stacken) [inline src/main/java/se/kth/iv1201/group4/recruitment/application/PersonService.java]: I think the debug level of this print could be lowered to at least info, as it should be fairly common for users to enter incorrect credentials.

Comment (Cactu5) [reply src/main/java/se/kth/iv1201/group4/recruitment/application/PersonService.java]: That sounds reasonable.

**Review by fiilp — APPROVED** [review]
👍

File: src/main/java/se/kth/iv1201/group4/recruitment/application/PersonService.java (hunk 2 above)
Comment (Cactu5) [reply src/main/java/se/kth/iv1201/group4/recruitment/application/PersonService.java]: I lowered it to debug level since there are probably going to be a lot of people that logs in with invalid credentials.
